apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: jenkins	
spec:
  containers:  
  - name: git
    image: makocchi/alpine-git-curl-jq
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json